name: Fix localisation
on:
  push:
    branches-ignore:
      - 'master'
jobs:
  fix_localisation:
    runs-on: ubuntu-latest
    steps:
    - name: Workflow run cleanup action
      uses: rokroskar/workflow-run-cleanup-action@v0.3.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEBUG: FALSE
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Fix locs
      uses: The24thDS/stellaris-localisation-crowdin-fix@v1.0.3
      with:
        localisation_folder: 'planet_states/localisation'
    - name: Check if there are changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11
    - name: Commit files
      if: steps.changes.outputs.changed == 1
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Autofix for localisation files"
        git push



